<?php

require_once 'crud/raelgc/view/Template.php';

class ViewCommand extends AbstractCommand
{
	public function run(array $args)
	{
		parent::run($args);
		$this->createView();
	}

	protected function createView()
	{
		$model = $this->model;
		$file = 'app/views/' . Inflector::uncamelize($model) . '/add.php';
		
		if(file_exists($file) && !$this->getOption('force')) {
			echo "Controller $name ja existe. Use --force para sobrescreve-lo.\n";
		    exit(1);
		}

		$tpl = new raelgc\view\Template('crud/template/view/add.tpl');
		
		foreach ($this->properties as $property => $annotation) {
			if(!$this->isAutoGenerated($property)) {
				$label = $property;
				if(isset($annotation->Label)) {
					$label = $annotation->Label;
				}
				$tpl->Label = $label;
				$tpl->Name = $property;
				$tpl->block('BLOCK_FIELDS');
			}
		}

		$content = $tpl->parse();

		$vars = array(
			'__MODEL__' => $model,
			'__model__' => Inflector::uncamelize($model, '_'),
			'__CONTROLLER__' => $name,
		);
		foreach ($vars as $key => $value) {
			$content = str_replace($key, $value, $content);
		}

		$directory = dirname($file);
		if(!is_dir($directory)) {
			if(!mkdir($directory, 0777)) {
				echo "Erro ao criar o diretorio {$directory}.\n";
				exit;
			}
			echo "Diretorio {$directory} criado.\n";
		}

		$success = file_put_contents($file, $content);

		if($success === false) {
			echo "Erro ao criar o arquivo $file.\n";
			exit(1);
		}
		echo "Arquivo $file criado.\n";
	}

	protected function loadTemplate($type, $vars = array())
	{
		$content = file_get_contents('crud/template/' . $type . '.tpl');
		foreach ($vars as $key => $value) {
			$content = str_replace($key, $value, $content);
		}
		return $content;
	}
}